"""initial schema with DIFC encryption

Revision ID: ef07c16c97aa
Revises: 
Create Date: 2026-02-03 20:47:40.384285

"""
from alembic import op
import sqlalchemy as sa
from utils.encryption import EncryptedType


# revision identifiers, used by Alembic.
revision = 'ef07c16c97aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create schemas first
    op.execute('CREATE SCHEMA IF NOT EXISTS "user"')
    op.execute('CREATE SCHEMA IF NOT EXISTS "accounts"')
    op.execute('CREATE SCHEMA IF NOT EXISTS "transactions"')
    op.execute('CREATE SCHEMA IF NOT EXISTS "system"')
    
    # Enable UUID extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', EncryptedType(length=500), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='account_status_enum'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_user_profiles_email'), 'user_profiles', ['email'], unique=True, schema='user')
    op.create_index(op.f('ix_user_user_profiles_username'), 'user_profiles', ['username'], unique=True, schema='user')
    op.create_table('user_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lean_account_id', sa.UUID(), nullable=True),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', EncryptedType(length=500), nullable=True),
    sa.Column('iban', EncryptedType(length=500), nullable=True),
    sa.Column('account_type', sa.Enum('CURRENT', 'SAVINGS', 'CREDIT', name='account_type_enum'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='account_status_enum'), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    schema='accounts'
    )
    op.create_index('idx_user_accounts_lean_account_id', 'user_accounts', ['lean_account_id'], unique=False, schema='accounts')
    op.create_index('idx_user_accounts_user_id', 'user_accounts', ['user_id'], unique=False, schema='accounts')
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('USER_LOGIN', 'DATA_EXPORT', 'CONSENT_GRANTED', 'CONSENT_REVOKED', 'ACCOUNT_DELETED', 'ADMIN_ACCESS', 'LEAN_SYNC', name='event_type_enum'), nullable=False),
    sa.Column('entity_type', sa.Enum('TRANSACTION', 'ACCOUNT', 'USER_PROFILE', 'CONSENT_RECORD', name='entity_type_enum'), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='system'
    )
    op.create_index('idx_audit_log_event_timestamp', 'audit_log', ['event_type', 'timestamp'], unique=False, schema='system', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('idx_audit_log_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False, schema='system', postgresql_ops={'timestamp': 'DESC'})
    op.create_table('consent_records',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('DATA_PROCESSING', 'OPEN_FINANCE_ACCESS', 'MARKETING', 'ANALYTICS', name='consent_type_enum'), nullable=False),
    sa.Column('consent_text_version', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id'),
    schema='user'
    )
    op.create_index('idx_consent_user_type_revoked', 'consent_records', ['user_id', 'consent_type', 'revoked_at'], unique=False, schema='user')
    op.create_table('data_ingestion_config',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_method', sa.Enum('REAL_TIME', 'MANUAL', name='ingestion_method_enum'), nullable=False),
    sa.Column('open_finance_provider', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('lean_access_token', EncryptedType(length=1000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('ACTIVE', 'PAUSED', 'FAILED', 'EXPIRED', name='sync_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='user'
    )
    op.create_table('user_demographics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='sex_enum'), nullable=True),
    sa.Column('income_estimate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('income_source', sa.Enum('USER_PROVIDED', 'AUTO_DETECTED', name='income_source_enum'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('age >= 18 AND age <= 100', name='age_check'),
    sa.CheckConstraint('income_estimate >= 0', name='income_estimate_check'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='user'
    )
    op.create_table('account_balances',
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.user_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('balance_id'),
    schema='accounts'
    )
    op.create_index('idx_account_balances_account_timestamp', 'account_balances', ['account_id', 'snapshot_timestamp'], unique=False, schema='accounts', postgresql_ops={'snapshot_timestamp': 'DESC'})
    op.create_table('credit_card_details',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('card_last_four', EncryptedType(length=100), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('next_payment_due_date', sa.Date(), nullable=True),
    sa.Column('next_payment_due_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('credit_limit > 0', name='credit_limit_check'),
    sa.CheckConstraint('next_payment_due_amount >= 0', name='payment_due_amount_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.user_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    schema='accounts'
    )
    op.create_table('raw_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('lean_transaction_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', EncryptedType(length=2000), nullable=True),
    sa.Column('description_cleansed', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('DEBIT', 'CREDIT', name='transaction_type_enum'), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('lean_insights_category', sa.String(length=50), nullable=True),
    sa.Column('lean_insights_type', sa.String(length=50), nullable=True),
    sa.Column('lean_category_confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('lean_category_confidence >= 0 AND lean_category_confidence <= 1', name='category_confidence_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.user_accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('lean_transaction_id'),
    schema='transactions'
    )
    op.create_index('idx_raw_transactions_account_date', 'raw_transactions', ['account_id', 'transaction_date'], unique=False, schema='transactions', postgresql_ops={'transaction_date': 'DESC'})
    op.create_index('idx_raw_transactions_lean_id', 'raw_transactions', ['lean_transaction_id'], unique=False, schema='transactions')
    op.create_index('idx_raw_transactions_user_date', 'raw_transactions', ['user_id', 'transaction_date'], unique=False, schema='transactions', postgresql_ops={'transaction_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_raw_transactions_user_date', table_name='raw_transactions', schema='transactions', postgresql_ops={'transaction_date': 'DESC'})
    op.drop_index('idx_raw_transactions_lean_id', table_name='raw_transactions', schema='transactions')
    op.drop_index('idx_raw_transactions_account_date', table_name='raw_transactions', schema='transactions', postgresql_ops={'transaction_date': 'DESC'})
    op.drop_table('raw_transactions', schema='transactions')
    op.drop_table('credit_card_details', schema='accounts')
    op.drop_index('idx_account_balances_account_timestamp', table_name='account_balances', schema='accounts', postgresql_ops={'snapshot_timestamp': 'DESC'})
    op.drop_table('account_balances', schema='accounts')
    op.drop_table('user_demographics', schema='user')
    op.drop_table('data_ingestion_config', schema='user')
    op.drop_index('idx_consent_user_type_revoked', table_name='consent_records', schema='user')
    op.drop_table('consent_records', schema='user')
    op.drop_index('idx_audit_log_user_timestamp', table_name='audit_log', schema='system', postgresql_ops={'timestamp': 'DESC'})
    op.drop_index('idx_audit_log_event_timestamp', table_name='audit_log', schema='system', postgresql_ops={'timestamp': 'DESC'})
    op.drop_table('audit_log', schema='system')
    op.drop_index('idx_user_accounts_user_id', table_name='user_accounts', schema='accounts')
    op.drop_index('idx_user_accounts_lean_account_id', table_name='user_accounts', schema='accounts')
    op.drop_table('user_accounts', schema='accounts')
    op.drop_index(op.f('ix_user_user_profiles_username'), table_name='user_profiles', schema='user')
    op.drop_index(op.f('ix_user_user_profiles_email'), table_name='user_profiles', schema='user')
    op.drop_table('user_profiles', schema='user')
    # ### end Alembic commands ###
    
    # Drop schemas
    op.execute('DROP SCHEMA IF EXISTS "system" CASCADE')
    op.execute('DROP SCHEMA IF EXISTS "transactions" CASCADE')
    op.execute('DROP SCHEMA IF EXISTS "accounts" CASCADE')
    op.execute('DROP SCHEMA IF EXISTS "user" CASCADE')
